# Generated by Django 4.1.7 on 2023-04-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('optional', models.DateTimeField(blank=True, null=True)),
                ('ready_or_not', models.BooleanField(default=False)),
                ('tags', models.ManyToManyField(related_name='tasks', to='list.tag')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
