# Generated by Django 4.1.7 on 2023-04-03 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_alter_tag_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='optional',
            new_name='deadline',
        ),
    ]
